### ISSUE TITLE
Drop 'X-' prefix from headers

### ISSUE THREAD

**Issue by nateabele** [unbit/spockfs#3]
According to [RFC 6648](https://tools.ietf.org/html/rfc6648), prefixing custom headers with `X-` has been deprecated.

Not trying to be pedantic, just figured I'd throw that out there. Lemme know if you'd like a PR.

**Comment by unbit** [comment]
Seems reasonable. Please make a pull request and upgrade SPECS to 2.0. I have added a section in the README for contributors/credits, feel free to add your name. Thanks a lot

**Comment by unbit** [comment]
I am about to update specs to 0.2, if you still want to make the pull request i will wait for it. Thanks

**Comment by nateabele** [comment]
Sorry for slackin'. I'll knock it out tonight. Thanks.

**Comment by unbit** [comment]
Sorry to bother you, some news ? If you want i can update specs and reference code and leave your credit without problems

**Comment by nateabele** [comment]
Sorry! See #5.

**Comment by nateabele** [comment]
Let me know if you want the C code updated also (I promise it won't take as long!).

**Comment by unbit** [comment]
Yes, you can update the code too, just use the same pull request and use your credits. Thanks

**Comment by nateabele** [comment]
Okay, done. PR updated.

**Comment by unbit** [comment]
Sorry mate, can you move the pull request to the 0.2 branch (just created it) ? i would like to introduce some more improvement for 0.2 (like specs for IOCTL and POLL). Thanks again

**Comment by nateabele** [comment]
Done. :-) No problem.

**Comment by nateabele** [comment]
Fixed in #6.
